# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a80dab322951a38e48032759d65cc2c0c968bda49e9669a41327760ea118a6c343bcaeb8121a548bd90c07eb141368cdfeb0f58d05486692bf14c39c9d3c54a3

test:
  secret_key_base: b7c7133bde7d6e35553a2a738248a3cc4b73c4934f16916be66b2fa59b2e6ea97ea3657cf1ead60c3f9c611fb8fff2cbae3ec1f042779c5388bd88aab61020d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
